"""Utah regions, cities and Hill Air Force Base."""
COST = "Nothing. Independent agents are paid by the carriers when you enroll, so comparing plans and reviewing your coverage each year is free to you."
NET = "Intermountain Health and University of Utah Health each contract with some Medicare Advantage plans and not others, and Select Health plans are built on Intermountain. With Original Medicare and a Medigap policy there is no network to check. We confirm your doctors before you enroll."

REGIONS = [
    dict(slug="salt-lake-valley", name="Salt Lake Valley", short="the Salt Lake Valley", scene="saltlake",
         eyebrow="Medicare by region · Salt Lake County",
         h1="Medicare help across the Salt Lake Valley",
         sub="Salt Lake City, West Valley, West Jordan, Sandy, Draper and the rest of Salt Lake County &mdash; the deepest plan menu in Utah, and a care map split four ways.",
         counties="Salt Lake, Tooele",
         cities=["salt-lake-city", "west-valley-city", "west-jordan", "sandy", "draper"],
         systems=["Intermountain Medical Center &amp; LDS Hospital", "University of Utah Hospital &amp; Huntsman Cancer Institute", "MountainStar: St. Mark&rsquo;s, Lone Peak, Jordan Valley", "Holy Cross (CommonSpirit)", "George E. Wahlen VA Medical Center"],
         note="<p><strong>Local plans to know:</strong> Select Health Medicare is built on Intermountain; University of Utah Health Plans on the U. UnitedHealthcare, Humana, Aetna, Cigna, Devoted Health and Regence BlueCross BlueShield of Utah contract with the systems in different combinations, and Salt Lake County typically has the most Advantage plans in the state.</p>",
         intro=["Salt Lake County holds a third of Utah&rsquo;s Medicare beneficiaries and the widest Advantage menu, and its care is divided among Intermountain, the University of Utah, MountainStar and Holy Cross. A $0-premium plan that covers Intermountain Medical Center may not cover Huntsman; a plan built on the U may not cover St. Mark&rsquo;s. That is the whole comparison, and it comes before price.",
                "The valley also holds the Wahlen VA and a large share of Hill Air Force Base retirees, so TRICARE For Life and VA coordination come up in a lot of our Salt Lake conversations."],
         faqs=[("Which Medicare plans are available in Salt Lake County?", "Salt Lake County typically offers the widest Medicare Advantage menu in Utah &mdash; Select Health, UnitedHealthcare, Humana, Aetna, Cigna, Devoted, Regence and others &mdash; every Medigap carrier in the state, and the full Part D lineup. Availability changes each plan year."),
               ("Is Huntsman Cancer Institute in my plan&rsquo;s network?", "Huntsman is part of University of Utah Health, which accepts Original Medicare and therefore any Medigap policy, and contracts with some Advantage plans and not others. We confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="utah-valley", name="Utah Valley", short="Utah Valley", scene="utahvalley",
         eyebrow="Medicare by region · Provo, Orem, Lehi &amp; Utah County",
         h1="Medicare help across Utah Valley",
         sub="Provo, Orem, Lehi, American Fork, Spanish Fork and the rest of Utah County &mdash; one of the fastest-growing Medicare markets in the West, with Intermountain&rsquo;s Utah Valley Hospital at its center.",
         counties="Utah, Juab, Wasatch (south)",
         cities=["provo", "orem", "lehi"],
         systems=["Intermountain Utah Valley Hospital", "Intermountain American Fork &amp; Orem Community", "MountainStar Timpanogos Regional", "Mountain Point Medical Center", "Provo VA Clinic"],
         note="<p><strong>What to watch:</strong> Utah County typically has more than two dozen Advantage plans, most at $0 premium. Intermountain dominates local care, so Select Health plans and any carrier that contracts with Intermountain cover most families; MountainStar Timpanogos and Mountain Point sit in different networks.</p>",
         intro=["Utah Valley&rsquo;s Medicare market is growing faster than almost any in the country, and its care is more concentrated than Salt Lake&rsquo;s: Intermountain runs Utah Valley Hospital, American Fork and Orem Community, with MountainStar&rsquo;s Timpanogos Regional and Mountain Point as the alternatives. For most families the question is whether a plan covers Intermountain; for the rest it is whether it covers Timpanogos.",
                "University of Utah specialists are forty minutes north, and a referral there is where an Intermountain-built Advantage plan can get complicated."],
         faqs=[("Which Medicare plans are available in Utah County?", "Utah County typically offers more than two dozen Medicare Advantage plans, most at $0 premium, plus every Medigap carrier in Utah and the full Part D lineup. Availability changes each plan year."),
               ("Are Intermountain and Timpanogos in the same plans?", NET),
               ("How much does your help cost?", COST)]),
    dict(slug="northern-utah", name="Northern Utah", short="Northern Utah", scene="bearlake",
         eyebrow="Medicare by region · Ogden, Layton, Logan &amp; Hill AFB",
         h1="Medicare help across Northern Utah",
         sub="Davis, Weber, Cache and Box Elder counties &mdash; Ogden, Layton, Bountiful, Logan, Brigham City, and the largest military-retiree community in the state around Hill Air Force Base.",
         counties="Davis, Weber, Cache, Box Elder, Morgan, Rich",
         cities=["ogden", "layton", "bountiful", "logan", "hill-afb"],
         systems=["Intermountain McKay-Dee (Ogden)", "Intermountain Layton", "MountainStar Ogden Regional", "Holy Cross Davis (Layton)", "Intermountain Logan Regional", "Cache Valley Hospital", "Ogden &amp; Logan VA clinics"],
         note="<p><strong>Local plans to know:</strong> Davis and Weber counties have a broad Advantage menu split between Intermountain (McKay-Dee, Layton) and MountainStar (Ogden Regional) and Holy Cross (Davis). Cache Valley&rsquo;s menu is shorter and built around Logan Regional. Hill AFB retirees with TRICARE For Life usually need little beyond Parts A and B.</p>",
         intro=["Northern Utah stacks four counties along I-15 and Cache Valley beyond it, and its Medicare map has three layers: a metro-style Advantage menu in Davis and Weber, a smaller one in Cache and Box Elder, and a TRICARE For Life community around Hill Air Force Base that changes what &ldquo;best plan&rdquo; means.",
                "McKay-Dee in Ogden and Layton Hospital are Intermountain; Ogden Regional is MountainStar; Holy Cross Davis is CommonSpirit. Which of those a plan includes is the first thing we check."],
         faqs=[("Which Medicare plans are available in Ogden and Layton?", "Davis and Weber counties typically offer a broad Medicare Advantage menu, every Medigap carrier in Utah, and the full Part D lineup. Cache and Box Elder counties have fewer Advantage plans. Availability changes each plan year."),
               ("I retired from Hill AFB with TRICARE For Life. What do I need?", "Usually just Medicare Parts A and B: TFL pays secondary and its pharmacy is creditable, so a Medigap policy and Part D are normally unnecessary. An MA-only Advantage plan can add dental or vision. See our Hill AFB page."),
               ("How much does your help cost?", COST)]),
    dict(slug="southern-utah", name="Southern Utah &amp; Dixie", short="Southern Utah", scene="redcliffs",
         eyebrow="Medicare by region · St. George, Cedar City, Hurricane &amp; Kanab",
         h1="Medicare help across Southern Utah and Dixie",
         sub="Washington, Iron and Kane counties &mdash; one of the fastest-growing retirement regions in America, St. George Regional at its center, and Mesquite and Las Vegas just over the line.",
         counties="Washington, Iron, Kane, Garfield, Beaver",
         cities=["st-george", "cedar-city"],
         systems=["Intermountain St. George Regional", "Intermountain Cedar City Hospital", "Kane County Hospital", "St. George VA Clinic", "Mesquite &amp; Las Vegas providers (Nevada)"],
         note="<p><strong>What to watch:</strong> Washington County&rsquo;s Advantage menu has grown with its population but is built almost entirely around Intermountain St. George Regional, and Molina&rsquo;s Utah Advantage footprint is now largely limited to this corner of the state. Many residents also see doctors in Mesquite or Las Vegas, which an Advantage network may not include.</p>",
         intro=["Southern Utah is where the rest of the state retires to, and Washington County&rsquo;s Medicare population has grown accordingly. Care is concentrated: Intermountain St. George Regional handles most of it, Cedar City Hospital serves Iron County, and anything more specialized means Salt Lake or Las Vegas. That makes the network question sharper than in the metros, and it is where a Medigap policy&rsquo;s any-provider access earns its premium.",
                "Because so many Dixie residents cross into Nevada for care, golf and winter, our <a href=\"https://medicareenrollmentnevada.com\">Nevada sister site</a> is part of the conversation here."],
         faqs=[("Which Medicare plans are available in St. George?", "Washington County typically offers a moderate Medicare Advantage menu built around Intermountain St. George Regional, every Medigap carrier in Utah, and the full Part D lineup. Availability changes each plan year."),
               ("Can I see a doctor in Mesquite or Las Vegas with a Utah plan?", "With Original Medicare and a Medigap policy, yes &mdash; any provider that accepts Medicare. With a Medicare Advantage plan, only if that provider is in-network, which we confirm before you enroll."),
               ("How much does your help cost?", COST)]),
    dict(slug="central-eastern-utah", name="Central &amp; Eastern Utah", short="Central and Eastern Utah", scene="arch",
         eyebrow="Medicare by region · Richfield, Price, Vernal, Moab &amp; the Uinta Basin",
         h1="Medicare help across Central and Eastern Utah",
         sub="Sevier, Carbon, Emery, Uintah, Duchesne, Grand and San Juan counties &mdash; small hospitals, long drives, and the thinnest Advantage menus in the state.",
         counties="Sevier, Sanpete, Millard, Carbon, Emery, Uintah, Duchesne, Grand, San Juan, Piute, Wayne",
         cities=[],
         systems=["Intermountain Sevier Valley (Richfield)", "Castleview Hospital (Price)", "Ashley Regional (Vernal)", "Uintah Basin Healthcare (Roosevelt)", "Moab Regional Hospital", "San Juan Health (Monticello, Blanding)"],
         note="<p><strong>What to watch:</strong> Several central and eastern counties have only a handful of Advantage plans, and networks that look fine on paper can mean a two-hour drive. Original Medicare with a Medigap policy covers every hospital in the region without a network, and that is often the practical answer out here.</p>",
         intro=["Rural Utah&rsquo;s Medicare problem is distance. Richfield, Price, Vernal, Roosevelt, Moab and Monticello each have a hospital, and anything beyond it means Provo, Salt Lake or Grand Junction. Advantage menus are short and networks thin, which is why so many families here keep Original Medicare with a Medigap policy and a Part D plan chosen around the local pharmacy.",
                "We serve every town in the region by phone and video, and we check the actual drive to an in-network specialist before we recommend a network plan."],
         faqs=[("Which Medicare plans are available in rural Utah?", "Central and eastern counties typically offer a handful of Medicare Advantage plans, every Medigap carrier in Utah, and the full Part D lineup. Availability varies by county and changes each plan year."),
               ("Is a Medigap policy better than Advantage in rural Utah?", "Often, because it covers every hospital in the state and in Grand Junction without a network. But the premium is real, and some rural Advantage plans are strong. We compare both against your doctors, drives and budget."),
               ("How much does your help cost?", COST)]),
    dict(slug="park-city-wasatch-back", name="Park City &amp; the Wasatch Back", short="the Wasatch Back", scene="aspens",
         eyebrow="Medicare by region · Park City, Heber, Kamas &amp; Midway",
         h1="Medicare help across Park City and the Wasatch Back",
         sub="Summit and Wasatch counties &mdash; second homes, skiers who retired here, Intermountain Park City and Heber Valley hospitals, and Salt Lake specialists over the pass.",
         counties="Summit, Wasatch",
         cities=["park-city"],
         systems=["Intermountain Park City Hospital", "Intermountain Heber Valley Hospital", "University of Utah &amp; Salt Lake specialists"],
         note="<p><strong>What to watch:</strong> A large share of Wasatch Back residents keep another home elsewhere, and county-based Advantage plans are tied to permanent residence. A Medigap policy travels; an HMO from Summit County covers emergencies only in Scottsdale.</p>",
         intro=["Park City and the Heber Valley have grown into a retirement region of their own, with Intermountain&rsquo;s Park City and Heber Valley hospitals for local care and Salt Lake&rsquo;s specialists forty minutes away. The Medicare question here is often a two-home question, and the answer usually starts with a Medigap policy.",
                "Summit and Wasatch counties&rsquo; Advantage menus are moderate and built mostly around Intermountain; we compare them honestly against a supplement with your travel in view."],
         faqs=[("Which Medicare plans are available in Park City?", "Summit and Wasatch counties typically offer a moderate Medicare Advantage menu built around Intermountain, every Medigap carrier in Utah, and the full Part D lineup. Availability changes each plan year."),
               ("I split the year between Park City and Scottsdale. What works?", "A Medigap policy with Original Medicare works in both places. County-based Advantage and Part D plans are tied to your permanent residence, and most Advantage HMOs cover only emergencies out of area. See our snowbird guide."),
               ("How much does your help cost?", COST)]),
]

def city(slug, name, county, region, scene, sub, intro, systems, communities, faqs, nearby):
    return dict(slug=slug, name=name, county=county, region=region, scene=scene, sub=sub, intro=intro, systems=systems, communities=communities, faqs=faqs, nearby=nearby)

CITIES = [
    city("salt-lake-city", "Salt Lake City", "Salt Lake County", "salt-lake-valley", "saltlake",
         "From the Avenues to Sugar House, Salt Lake City has Utah&rsquo;s deepest plan menu &mdash; and a care map where Intermountain, the University of Utah, MountainStar and Holy Cross each contract on their own terms.",
         ["Salt Lake County offers the widest Advantage menu in Utah, every Medigap carrier licensed in the state and the full Part D lineup. The trade-off is that a plan built on Intermountain (Select Health, and carriers that contract with it) may exclude University of Utah Hospital and Huntsman, and a plan built on the U may exclude LDS Hospital and Intermountain Medical Center. The network is the whole question.",
          "We compare what is actually offered at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy so the trade-off is plain."],
         ["Intermountain Medical Center (Murray)", "LDS Hospital", "University of Utah Hospital", "Huntsman Cancer Institute", "St. Mark&rsquo;s Hospital (MountainStar)", "Holy Cross Salt Lake", "George E. Wahlen VA Medical Center"],
         "The Avenues, Sugar House, Rose Park, Millcreek, Holladay, Murray, South Salt Lake, Cottonwood Heights, Magna",
         [("Which Medicare plans are available in Salt Lake City?", "Salt Lake County typically has the widest choice in Utah: Medicare Advantage plans from Select Health, UnitedHealthcare, Humana, Aetna, Cigna, Devoted, Regence and others, every Medigap carrier in the state, and all standalone Part D plans. Availability changes each plan year."),
          ("Will my University of Utah or Intermountain doctors take a Medicare Advantage plan?", NET),
          ("How much does your help cost?", COST)],
         ["west-valley-city", "sandy", "bountiful"]),
    city("west-valley-city", "West Valley City", "Salt Lake County", "salt-lake-valley", "saltlake",
         "West Valley, Magna, Kearns and Taylorsville have the full Salt Lake County menu, Jordan Valley Medical Center close by, and a large share of the valley&rsquo;s dual-eligible households.",
         ["West-side residents have Salt Lake County&rsquo;s broad Advantage menu, every Medigap carrier in Utah and the full Part D lineup. Jordan Valley (Holy Cross), Intermountain Medical Center and St. Mark&rsquo;s each contract differently, and many west-side families qualify for both Medicare and Utah Medicaid, which makes Dual Special Needs Plans part of the conversation.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and check whether a Medicare Savings Program applies."],
         ["Holy Cross Jordan Valley (West Jordan)", "Intermountain Medical Center", "St. Mark&rsquo;s Hospital", "Intermountain clinics"],
         "West Valley City, Magna, Kearns, Taylorsville, Granger, Hunter",
         [("Which Medicare plans are available in West Valley City?", "The full Salt Lake County lineup: a wide Medicare Advantage menu including Dual Special Needs Plans, every Medigap carrier in Utah, and the full Part D lineup."),
          ("Can Utah Medicaid help pay my Part B premium?", "Possibly. Utah&rsquo;s Medicare Savings Programs pay the Part B premium for people with limited income and resources; apply through the Department of Workforce Services. See our Utah Medicaid page."),
          ("How much does your help cost?", COST)],
         ["salt-lake-city", "west-jordan"]),
    city("west-jordan", "West Jordan", "Salt Lake County", "salt-lake-valley", "wasatch",
         "West Jordan, South Jordan, Riverton and Herriman are the fastest-growing part of the valley, with Jordan Valley, Intermountain Riverton and Lone Peak all nearby and in different networks.",
         ["Southwest-valley residents have the county&rsquo;s broad Advantage menu, every Medigap carrier in Utah and the full Part D lineup. Holy Cross Jordan Valley, Intermountain Riverton and MountainStar Lone Peak sit within minutes of each other and in three different network families; which one your doctors belong to decides the shortlist.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Holy Cross Jordan Valley", "Intermountain Riverton Hospital", "Lone Peak Hospital (MountainStar)", "Intermountain clinics"],
         "West Jordan, South Jordan, Daybreak, Riverton, Herriman, Bluffdale, Copperton",
         [("Which Medicare plans are available in West Jordan?", "The full Salt Lake County lineup of Medicare Advantage, Medigap and Part D plans, set by ZIP code and changing each plan year."),
          ("Are Jordan Valley, Riverton and Lone Peak in the same plans?", NET),
          ("How much does your help cost?", COST)],
         ["west-valley-city", "sandy", "draper"]),
    city("sandy", "Sandy", "Salt Lake County", "salt-lake-valley", "wasatch",
         "Sandy, Midvale and Cottonwood Heights sit at the foot of the Wasatch with Alta View and Intermountain Medical Center close by and the full county plan menu.",
         ["Southeast-valley residents have Salt Lake County&rsquo;s broad Advantage menu, every Medigap carrier in Utah and the full Part D lineup. Intermountain Alta View and Intermountain Medical Center anchor local care, with St. Mark&rsquo;s and the U a short drive north in different networks.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Intermountain Alta View Hospital", "Intermountain Medical Center", "St. Mark&rsquo;s Hospital", "University of Utah Health"],
         "Sandy, Midvale, Cottonwood Heights, White City, Granite, Union",
         [("Which Medicare plans are available in Sandy?", "The full Salt Lake County lineup of Medicare Advantage, Medigap and Part D plans, set by ZIP code and changing each plan year."),
          ("Is Alta View in my plan&rsquo;s network?", NET),
          ("How much does your help cost?", COST)],
         ["draper", "salt-lake-city", "west-jordan"]),
    city("draper", "Draper", "Salt Lake County", "salt-lake-valley", "wasatch",
         "Draper straddles the county line, which matters: Salt Lake County and Utah County have different Advantage menus, and Lone Peak and Alta View are in different networks.",
         ["Draper residents in Salt Lake County have the county&rsquo;s broad Advantage menu; the Utah County side of town has Utah County&rsquo;s. Both have every Medigap carrier in Utah and the full Part D lineup. MountainStar Lone Peak and Intermountain Alta View are the nearest hospitals and belong to different network families.",
          "We check which county your address is in first, then compare what is sold there."],
         ["Lone Peak Hospital (MountainStar)", "Intermountain Alta View", "Intermountain Riverton", "Utah Valley specialists"],
         "Draper, Suncrest, Bluffdale, Riverton, Lehi border",
         [("Which Medicare plans are available in Draper?", "It depends on which county your address is in; Salt Lake and Utah counties have different Medicare Advantage menus. Both have every Medigap carrier in Utah and the full Part D lineup."),
          ("Is Lone Peak in my plan&rsquo;s network?", NET),
          ("How much does your help cost?", COST)],
         ["sandy", "lehi", "west-jordan"]),
    city("provo", "Provo", "Utah County", "utah-valley", "utahvalley",
         "Provo is Intermountain country: Utah Valley Hospital handles most care, and the Advantage menu is one of the broadest in the state with most plans at $0 premium.",
         ["Utah County offers more than two dozen Advantage plans, every Medigap carrier in Utah and the full Part D lineup. Intermountain Utah Valley Hospital dominates local care, so Select Health plans and carriers that contract with Intermountain cover most Provo families; a referral to the University of Utah is where an Intermountain-built plan can get complicated.",
          "We compare what is sold at your ZIP code, confirm your doctors and pharmacy, and set Advantage beside a Medigap policy."],
         ["Intermountain Utah Valley Hospital", "Intermountain clinics", "Provo VA Clinic", "University of Utah specialists (Salt Lake)"],
         "Provo, Springville, Spanish Fork, Mapleton, Salem, Payson, Vineyard",
         [("Which Medicare plans are available in Provo?", "Utah County typically offers more than two dozen Medicare Advantage plans, most at $0 premium, plus every Medigap carrier in Utah and the full Part D lineup."),
          ("Does Utah Valley Hospital take my Advantage plan?", NET),
          ("How much does your help cost?", COST)],
         ["orem", "lehi"]),
    city("orem", "Orem", "Utah County", "utah-valley", "utahvalley",
         "Orem, Lindon and Pleasant Grove have Utah County&rsquo;s broad menu, Intermountain Orem Community and Timpanogos Regional nearby, and in different networks.",
         ["Utah County offers a wide Advantage menu, every Medigap carrier in Utah and the full Part D lineup. Intermountain Orem Community and Utah Valley Hospital are Intermountain; Timpanogos Regional is MountainStar, so which system your doctors belong to decides the shortlist.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Intermountain Orem Community Hospital", "MountainStar Timpanogos Regional", "Intermountain Utah Valley Hospital"],
         "Orem, Lindon, Pleasant Grove, Vineyard, Cedar Hills, American Fork",
         [("Which Medicare plans are available in Orem?", "Utah County typically offers more than two dozen Medicare Advantage plans, every Medigap carrier in Utah and the full Part D lineup."),
          ("Are Orem Community and Timpanogos in the same plans?", NET),
          ("How much does your help cost?", COST)],
         ["provo", "lehi"]),
    city("lehi", "Lehi", "Utah County", "utah-valley", "wasatch",
         "Lehi, Saratoga Springs and Eagle Mountain are the fastest-growing corner of Utah County, with Mountain Point, Intermountain American Fork and Salt Lake&rsquo;s systems all within reach.",
         ["North Utah County has the county&rsquo;s broad Advantage menu, every Medigap carrier in Utah and the full Part D lineup. Mountain Point Medical Center, Intermountain American Fork and the Salt Lake systems over the Point of the Mountain contract differently; we check which your doctors belong to first.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Mountain Point Medical Center", "Intermountain American Fork Hospital", "Lone Peak Hospital (MountainStar)", "Intermountain clinics"],
         "Lehi, Saratoga Springs, Eagle Mountain, American Fork, Highland, Alpine, Cedar Fort",
         [("Which Medicare plans are available in Lehi?", "Utah County typically offers more than two dozen Medicare Advantage plans, every Medigap carrier in Utah and the full Part D lineup."),
          ("Is Mountain Point in my plan&rsquo;s network?", NET),
          ("How much does your help cost?", COST)],
         ["draper", "orem", "provo"]),
    city("st-george", "St. George", "Washington County", "southern-utah", "redcliffs",
         "St. George is where Utah retires, and its Medicare market has grown with it: a moderate Advantage menu built around Intermountain St. George Regional, and Nevada twenty minutes away.",
         ["Washington County offers a moderate Advantage menu, every Medigap carrier in Utah and the full Part D lineup. Intermountain St. George Regional handles most local care; specialty care means Salt Lake or Las Vegas, and many residents see doctors in Mesquite, which an Advantage network may not include.",
          "Because St. George households winter locally, travel to Nevada and Arizona, and retire here from the Wasatch Front, we compare Advantage against a Medigap policy with the map in front of us."],
         ["Intermountain St. George Regional Hospital", "Intermountain clinics", "St. George VA Clinic", "Mesquite &amp; Las Vegas providers (Nevada)"],
         "St. George, Washington, Hurricane, Ivins, Santa Clara, Sun River, SunRiver, Leeds, La Verkin",
         [("Which Medicare plans are available in St. George?", "Washington County typically offers a moderate Medicare Advantage menu built around Intermountain St. George Regional, every Medigap carrier in Utah, and the full Part D lineup. Availability changes each plan year."),
          ("Can I see a doctor in Mesquite or Las Vegas with a St. George plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if the Nevada provider is in-network, which we confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["cedar-city", "provo"]),
    city("cedar-city", "Cedar City", "Iron County", "southern-utah", "hoodoos",
         "Cedar City and Iron County have a short Advantage menu, Intermountain Cedar City Hospital, and long drives to anything more specialized.",
         ["Iron County offers a handful of Advantage plans, every Medigap carrier in Utah and the full Part D lineup. Intermountain Cedar City Hospital handles local care, with St. George an hour south and Salt Lake three hours north for specialists, which is where a Medigap policy&rsquo;s any-provider access earns its premium.",
          "We compare what is sold at your ZIP code and check the actual drive to an in-network specialist before recommending a network plan."],
         ["Intermountain Cedar City Hospital", "Intermountain St. George Regional", "Cedar City VA services"],
         "Cedar City, Enoch, Parowan, Brian Head, Kanarraville, Beaver-area families",
         [("Which Medicare plans are available in Cedar City?", "Iron County typically offers a handful of Medicare Advantage plans, every Medigap carrier in Utah, and the full Part D lineup. Availability changes each plan year."),
          ("Is a Medigap policy better than Advantage in Cedar City?", "Often, because it covers Cedar City, St. George and Salt Lake hospitals without a network. But the premium is real. We compare both against your doctors, drives and budget."),
          ("How much does your help cost?", COST)],
         ["st-george"]),
    city("ogden", "Ogden", "Weber County", "northern-utah", "bearlake",
         "Ogden has two hospitals in two networks &mdash; Intermountain McKay-Dee and MountainStar Ogden Regional &mdash; a broad Advantage menu, and Hill AFB retirees next door.",
         ["Weber County offers a broad Advantage menu, every Medigap carrier in Utah and the full Part D lineup. McKay-Dee is Intermountain and Ogden Regional is MountainStar, so which one your doctors belong to decides the shortlist; Hill AFB retirees with TRICARE For Life usually need little beyond Parts A and B.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Intermountain McKay-Dee Hospital", "MountainStar Ogden Regional", "Ogden VA Clinic", "Intermountain clinics"],
         "Ogden, South Ogden, Roy, Riverdale, North Ogden, Pleasant View, Harrisville, Huntsville",
         [("Which Medicare plans are available in Ogden?", "Weber County typically offers a broad Medicare Advantage menu, every Medigap carrier in Utah, and the full Part D lineup. Availability changes each plan year."),
          ("Are McKay-Dee and Ogden Regional in the same plans?", NET),
          ("How much does your help cost?", COST)],
         ["layton", "hill-afb", "logan"]),
    city("layton", "Layton", "Davis County", "northern-utah", "hillafb",
         "Layton, Clearfield and Syracuse are Hill Air Force Base&rsquo;s neighborhoods, with Intermountain Layton and Holy Cross Davis nearby and a Medicare question that usually starts with TRICARE For Life.",
         ["Davis County offers a broad Advantage menu, every Medigap carrier in Utah and the full Part D lineup. Intermountain Layton Hospital and Holy Cross Davis contract differently, and a large share of Layton households are Hill AFB retirees whose TRICARE For Life changes the calculation entirely.",
          "We compare what is sold at your ZIP code and, for TFL families, check whether an MA-only plan&rsquo;s extras are worth having."],
         ["Intermountain Layton Hospital", "Holy Cross Davis Hospital", "Hill AFB 75th Medical Group (TRICARE)", "Intermountain McKay-Dee"],
         "Layton, Clearfield, Syracuse, Kaysville, Farmington, Clinton, West Point, Sunset",
         [("Which Medicare plans are available in Layton?", "Davis County typically offers a broad Medicare Advantage menu, every Medigap carrier in Utah, and the full Part D lineup. Availability changes each plan year."),
          ("I retired from Hill AFB with TRICARE For Life. Do I need Medigap or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable. An MA-only Advantage plan can add dental or vision. See our Hill AFB page."),
          ("How much does your help cost?", COST)],
         ["hill-afb", "ogden", "bountiful"]),
    city("bountiful", "Bountiful", "Davis County", "northern-utah", "wasatch",
         "Bountiful, Centerville and North Salt Lake sit between Salt Lake and Davis County&rsquo;s hospitals, with Holy Cross Davis, LDS Hospital and Intermountain Layton all within reach.",
         ["South Davis County has the county&rsquo;s broad Advantage menu, every Medigap carrier in Utah and the full Part D lineup, and residents split their care between Davis County and Salt Lake. Holy Cross Davis, Intermountain Layton and Salt Lake&rsquo;s LDS Hospital and the U contract differently.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Holy Cross Davis Hospital", "LDS Hospital (Intermountain)", "Intermountain Layton", "University of Utah Health"],
         "Bountiful, Centerville, North Salt Lake, Woods Cross, West Bountiful, Farmington",
         [("Which Medicare plans are available in Bountiful?", "Davis County typically offers a broad Medicare Advantage menu, every Medigap carrier in Utah, and the full Part D lineup."),
          ("Can I use Salt Lake hospitals with a Davis County plan?", "With Original Medicare and a Medigap policy, yes. With a Medicare Advantage plan, only if the Salt Lake provider is in-network, which we confirm before you enroll."),
          ("How much does your help cost?", COST)],
         ["salt-lake-city", "layton"]),
    city("logan", "Logan", "Cache County", "northern-utah", "bearlake",
         "Cache Valley has a shorter Advantage menu than the Wasatch Front, Intermountain Logan Regional and Cache Valley Hospital in different networks, and Idaho a few miles north.",
         ["Cache County offers a moderate Advantage menu, every Medigap carrier in Utah and the full Part D lineup. Logan Regional is Intermountain and Cache Valley Hospital is independent, and residents of the Idaho side of the valley face a state-line question that a Medigap policy answers automatically.",
          "We compare what is sold at your ZIP code and set Advantage beside a Medigap policy."],
         ["Intermountain Logan Regional Hospital", "Cache Valley Hospital", "Logan VA Clinic"],
         "Logan, North Logan, Smithfield, Hyrum, Providence, Nibley, Wellsville, Brigham City-area families",
         [("Which Medicare plans are available in Logan?", "Cache County typically offers a moderate Medicare Advantage menu, every Medigap carrier in Utah, and the full Part D lineup. Availability changes each plan year."),
          ("Are Logan Regional and Cache Valley Hospital in the same plans?", NET),
          ("How much does your help cost?", COST)],
         ["ogden", "layton"]),
    city("park-city", "Park City", "Summit County", "park-city-wasatch-back", "aspens",
         "Park City retirees are often two-home households, with Intermountain Park City Hospital for local care, Salt Lake over the pass, and a plan question that starts with where you spend the winter and the summer.",
         ["Summit County offers a moderate Advantage menu built mostly around Intermountain, every Medigap carrier in Utah and the full Part D lineup. Because county-based plans are tied to permanent residence and many Park City households keep a second home, a Medigap policy is often the practical choice.",
          "We compare Advantage against a supplement with your calendar and your doctors in front of us."],
         ["Intermountain Park City Hospital", "Intermountain Heber Valley Hospital", "University of Utah Health (Salt Lake)"],
         "Park City, Snyderville, Kimball Junction, Jeremy Ranch, Kamas, Heber City, Midway",
         [("Which Medicare plans are available in Park City?", "Summit County typically offers a moderate Medicare Advantage menu built around Intermountain, every Medigap carrier in Utah, and the full Part D lineup."),
          ("I keep a second home out of state. Which plan works?", "A Medigap policy with Original Medicare works anywhere in the U.S. County-based Advantage and Part D plans are tied to your permanent residence, and most Advantage HMOs cover only emergencies out of area. See our snowbird guide."),
          ("How much does your help cost?", COST)],
         ["salt-lake-city", "sandy"]),
]

BASES = [
    dict(slug="hill-afb", name="Hill Air Force Base", region="northern-utah", scene="hillafb",
         title="Medicare Near Hill Air Force Base, UT | ECOS Medicare Solutions",
         desc="Medicare for Air Force retirees and veterans around Hill AFB, Layton, Clearfield and Ogden: TRICARE For Life, the 75th Medical Group, the Wahlen VA, and which plans fit. From a retired Air Force officer.",
         h1="Medicare near Hill Air Force Base",
         sub="Northern Utah has the state&rsquo;s largest military-retiree community. TRICARE For Life, the 75th Medical Group clinic, the Wahlen VA in Salt Lake and its Ogden clinic &mdash; and a Medicare decision that looks different from a civilian one, explained by a retired Air Force officer.",
         h2="Why the Medicare choice is different for a Hill AFB family",
         intro=["Davis and Weber counties hold thousands of Air Force retirees, and most of them reach 65 with TRICARE For Life waiting. TFL requires Medicare Parts A and B and then pays secondary to Medicare, so a Medigap policy is usually unnecessary; its pharmacy is creditable, so a Part D plan usually is too. What is left to decide is whether an MA-only Advantage plan adds dental, vision or hearing worth having &mdash; without duplicating the drug coverage you already have &mdash; and whether its network includes McKay-Dee, Layton or Ogden Regional.",
                "Veterans without TRICARE use the George E. Wahlen VA in Salt Lake and the Ogden clinic, and here the Part B timing question is the one that matters: VA care is not creditable for Part B, so delaying Part B because you have the VA triggers a lifelong penalty. The 75th Medical Group on base sees retirees on a space-available basis; it is not a substitute for Medicare."],
         systems=["Hill AFB 75th Medical Group (TRICARE)", "George E. Wahlen VA Medical Center (Salt Lake) &amp; Ogden VA Clinic", "Intermountain Layton Hospital", "Intermountain McKay-Dee (Ogden)", "Holy Cross Davis", "MountainStar Ogden Regional"],
         communities="Layton, Clearfield, Syracuse, Roy, Sunset, Clinton, South Weber, Riverdale, Kaysville, Ogden",
         faqs=[("I retired from the Air Force with TRICARE For Life. Do I need a Medigap policy or Part D?", "Usually neither. TFL pays secondary to Medicare and its pharmacy is creditable drug coverage. An MA-only Advantage plan can add dental or vision without duplicating your drug benefit; we check whether one is worth it for you."),
               ("I use the Wahlen VA. Do I still need Part B?", "In most cases, yes. VA medical care is not creditable coverage for Part B, so delaying it can trigger a permanent penalty and leaves you without coverage at a non-VA hospital. Enroll on time."),
               ("Can I keep using the clinic on base after 65?", "Retirees can be seen at the 75th Medical Group on a space-available basis under TRICARE rules; Medicare does not pay there. Most Hill AFB retirees pair TFL with civilian care at Intermountain Layton, McKay-Dee or Ogden Regional.")],
         nearby=["layton", "ogden", "bountiful"], cta="Retired from Hill? Let&rsquo;s sort out TRICARE, the VA and Medicare together."),
]
